service: alarmbot
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  alarm:
    handler: handler.alarm
    events:
      - schedule: cron(48 1 * * ? *)
